### ISSUE TITLE
Handle missing images

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#138]
During imageset creation, images frequently don't completely download or are unavailable from their source for various reasons (network errors, registry downtime, image deletion). Erroring and exiting due to missing or corrupted images is unacceptable at any point during a multi-hundred gigabyte operation. 

1. Attempt to redownload any files suffixed by `.download`, as these will crash the publisher. 
2. Output an error report of items that failed to download at the end of operation (stdout or user specified output directory)
3. Do not add failed items to metadata, so that the images can be reattempted to be processed normally if needed during the application's subsequent runs.

**Comment by jpower432** [comment]
@afflom, this can be closed, in my opinion. Since we track with association gathering, missing images will never be added but skipped over. #476 captures the `--skip-missing` flag correction, but right now this is still functional with `--continue-on-error`. The only criteria not fulfilled is the report, although the skipped images are logged as a warning.
