### ISSUE TITLE
RFE improve CLI clarity for obtain and publish images

### ISSUE THREAD

**Issue by SDBrett** [openshift/oc-mirror#187]
I think that the current CLI lacks clarity between the pull and publish tasks
To obtain content I would run `oc-mirror --config imageset.yaml file://output-dir` but no where does this command say that I'm obtaining.
To publish content to a mirror I would run `oc-mirror --from ./output-dir/file.tar registry:5000` but the command doesn't indicate what task I'm doing.

If the intention is to have obtain and publish as two separate tasks then we could make things a lot clearing by using CLI arguments for example: 

`oc-mirror obtain --config imageset.yaml  --dest file://output-dir`
`oc-mirror publish --source ./output-dir/file.tar --dest registry:5000`

Additionally, why is the destination for obtaining images have the prefix `file://....` but the prefix is not needed for publishing?

Thanks

**Comment by jpower432** [comment]
@SDBrett Thanks for your comment! We have a requirement to support mirror to mirror use cases which is why we changed the UX to an `oc-mirror [DEST]` format. We are trying to change the perception from `create` and `publish` phases to mirroring to and from sources and destinations. For example, mirror to disk, mirror registry to registry, mirror from disk to registry. Are you suggesting we change the destination argument to a flag to clear up some confusion?

**Comment by afflom** [comment]
Only thing I would add here is that oc-mirror is a plug-in to oc, so the command would be executed as `oc mirror --config path/to file://path/to/output`. when called as a plug-in, mirror becomes the command verb.

**Comment by afflom** [comment]
https://github.com/openshift/oc-mirror/issues/183

**Comment by SDBrett** [comment]
> 

Thanks for the info, I think the perception is playing a big part here as my view was obtain (or download) to as a cache, not mirrored to disk
