### ISSUE TITLE
[RFE] Mirror to s3

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#307]
Add an oc-mirror scheme that supports mirroring to/from s3.

**Comment by dmc5179** [comment]
This is the command that I've used to mirror to S3:
```
oc adm release mirror -a ./pull-secret.txt --from=quay.io/openshift-release-dev/ocp-release:4.7.0-x86_64 --to=s3://s3.amazonaws.com/$AWS_DEFAULT_REGION/${S3_BUCKET}/ocp-release
```

One thing I found with this command is that it always returns an error at the end. I will receive an error like:

```
unable to upload blob sha256:daefd6c4b0607ef2b5c6ffbf30f51ebf8eb9ff40ac205f5bbfd3b0ec558d6010 to s3://s3.amazonaws.com/ocp-release: blob already exists in the target location
```
I've never used an S3 clone to build a cluster so I cannot say if this is a breaking error or if it can be ignore. Since the blob already exists and is presumably used by more than one image, I would assume the resulting mirror should work fine. Just wanted to share what I've seen mirroring to S3.

**Comment by afflom** [comment]
Thank you for providing this info. I didnt actually know that oc adm release mirror had this capability.

**Comment by cooktheryan** [comment]
:+1: we could use this as an intermediary for mirroring at scale
