### ISSUE TITLE
[RFE] ability to filter the mirroring by os/arch

### ISSUE THREAD

**Issue by ianwatsonrh** [openshift/oc-mirror#327]
oc image mirror allows you to specify a filter-by-os os/arch flag which only mirrors across images of a certain architecture.

This is used to reduce the amount of images that are downloaded. 

This change is to enable this functionality by pushing the option up into oc-mirror.

From initial investigation there are 4 places where this change is required. 

./cli/mirror/options.go In here a new a new variable for 'filter-by-os' is added which defaults to .*
OR
./config/v1alpha1/config_types.go In here a new variable for 'filter-by-os' is added which defaults to .*

./cli/mirror/operator.go:	a.FilterOptions = imagemanifest.FilterOptions{FilterByOS: ".*"}
./cli/mirror/additional.go:	opts.FilterOptions = imagemanifest.FilterOptions{FilterByOS: ".*"}
./cli/mirror/publish.go:	genOpts.FilterOptions = imagemanifest.FilterOptions{FilterByOS: ".*"}

In these 3 places the variable is now mapped. 

For complete testing it would be ideal to push a manifest lists which contains several os/arch's, into the same repositories used in the current e2e testing.

**Comment by jpower432** [comment]
Just wanted to comment on the limitation here right now.

Because images in the catalog are statically referenced by digest, we do not allow filtering for mirroring.

Possible solutions:
1. Sparse manifest lists are allowed by registries
2. Multi-arch management moves into images that can be rewritten on mirror (i.e. the bundle images themselves, not the images referenced inside of the bundle images).
3. Allow ICSPs to mirror by tag (this is a current OpenShift enhancement)
