### ISSUE TITLE
[BUG] oc-mirror does not catch invalid registry input when a namespace is specified

### ISSUE THREAD

**Issue by jpower432** [openshift/oc-mirror#382]
# Version

```console
$ oc-mirror version
Client Version: version.Info{Major:"0", Minor:"2", GitVersion:"v0.2.0-alpha.1", GitCommit:"c732df4804f571b3d6a01aa24d58fed22c495129", GitTreeState:"clean", BuildDate:"2022-03-23T11:33:16Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

# What happened?

`oc-mirror` does not catch invalid registries if a namespace is specified

Example

```
oc-mirror --config ~/configs/imageset-config.yaml docker://registry:5000
error: destination registry must consist of registry host and namespace(s) only
```

This error was at a different point because the invalid registry was never caught. The input is seen as a namespace and not a registry, so the resolver defaulted to `docker.io`, causing the below failure.
```
oc-mirror --config ~/configs/imageset-config.yaml docker://registry:5000/test
error: error rebuilding catalog images from file-based catalogs: POST https://index.docker.io/v2/test/redhat/redhat-operator-index/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:test/redhat/redhat-operator-index Type:repository] map[Action:push Class: Name:test/redhat/redhat-operator-index Type:repository]]
```

# What did you expect to happen?

The registry to be seen as invalid with or without a namespace.

# How to reproduce it (as minimally and precisely as possible)?

See above.

# Anything else we need to know?

Specifying an FQDN solves this issue as a workaround.

# References

/kind bug

**Comment by d10n** [comment]
When the destination is docker://[...], mirror.go uses imagesource.ParseReference from openshift/oc, which uses reference.Parse from openshift/library-go.
The difference in expectations here is because "registry" or "registry:5000" looks like "image" or "image:tag".
I don't think we want to change library-go because that could have a ripple of unintended results, so I think either:
* we can customize the parsing for just oc-mirror, to make our possibly-common use case a little simpler, or
* treat this as a documentation/FAQ update, to preserve the expectations of the format for users across the ecosystem

But I think we should make an explicit decision with that consideration.
Thoughts?

**Comment by jpower432** [comment]
@d10n I would prefer the latter option for now. If any code changes would need to be made here, perhaps a better error message.
