### ISSUE TITLE
The defaultChannel for an operator should be valid when filtering a package using min/maxVersion  

### ISSUE THREAD

**Issue by joehuizenga** [openshift/oc-mirror#453]
The current implementation of oc-mirror allows an ISC to specify a min/max version of a package

There are situations where specifying a range results in an invalid defaultChannel being specified in the “olm.package” object which makes the catalog invalid 

```
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  local:
    path: /root/mirror
mirror:
  operators:
    - catalog: icr.io/cpopen/ibm-operator-catalog:fbc-latest
      full: false
      packages:
        - name: ibm-mq
          minVersion: '1.6.0'
          maxVersion: ‘1.7.0’
```

```
oc-mirror --config imageset-ibm-mq.yaml file://output --dry-run --skip-cleanup
```

produces an index.json that has the defaultChannel set to a channel
```
{
    "schema": "olm.package",
    "name": "ibm-mq",
    "defaultChannel": "v1.8",
…
}
```

This RFE is asking that oc-mirror enhance the operator min/maxVersion functionality to also determine/set the defaultChannel for a package that specifies a range.

Possible highlevel logic:

get the maxVersion for a package from the ISC (1.7.0)
find the olm.channel  that has an entry where package.maxVersion = olm.channel.entries[].name  //name includes this version (ibm-mq.v1.7.0)
  maxVersionChannelName = v1.7
get the current defaultChannel(v1.8) if != to one you found above (v1.7), replace it

{
    "schema": "olm.package",
    "name": "ibm-mq",
    "defaultChannel": "v1.7”,
     …
}

open questions:
what to do if there are multiple olm.channels that contain the same package/version? which one should be chosen as the default?
```
{
    "schema": "olm.channel",
    "name": "v1.7",
    "package": "ibm-mq",
    "entries": [
        {
            "name": "ibm-mq.v1.7.0",
            "skipRange": ">=1.0.0 <1.7.0"
        }
    ]
}

{
    "schema": "olm.channel",
    "name": “joes-channel”,
    "package": "ibm-mq",
    "entries": [
        {
            "name": "ibm-mq.v1.7.0",
            "skipRange": ">=1.0.0 <1.7.0"
        }
    ]
}
```

**Comment by joehuizenga** [comment]
@jpower432 I think that in last weeks oc-mirror workgroup there was mention that maybe the short term fix here was to change default channel validation so that a channel without a bundle attached did not generate a validation error.  I am not "liking" this path. I believe OLM uses the "default channel" to select dependent operators, seems like this would lead to some complications at run-time

**Comment by jpower432** [comment]
The PR I submitted here #464 is the short term fix.
It will verify the validity of the index during the planning phase to ensure the default channel is not filtered out.

As to the long term fix, the plan is to consult with the OLM team. Whether the default channel with a bundle is required for dependency resolution, I will defer to @dinhxuanvu.

**Comment by dinhxuanvu** [comment]
Hi Joe. I just want to say a few things here. First of all, mirror doesn't have the authority to randomly choose another channel to be the new default channel when the default channel is missing. That authority is on the operator author or pipeline/packaging owner. The default channel does matter in OLM world so the decision of which channel is the default one shouldn't be taken slightly and should solely rest on who owns it. Secondly, at the moment, FBC validation does not allow empty channel so that will lead to empty channel to be pruned in case there are no valid bundles in the default or any channel. This is perhaps something I can talk to my team to see if we can relax this restriction. However, this is subject to further discussion so there is no guarantee here. Because of these two reasons, the appropriate action here for oc-mirror to do when default channel missing is to error out. That will ensure customers have option to modify the config and rerun if needed.

**Comment by joehuizenga** [comment]
Hi @dinhxuanvu  thanks for your input, I can see where having oc-mirror "try" to choose a new default channel could be risky. I think I am ok with it failing as well, what I am struggling with, is there doesn't seem to be a good way to stop this from happening or fixing it if it does. In our use cases for oc-mirror, our product teams would be the ones delivering imagesetconfigs as input to oc-mirror, they know what the defaultchannel should be when a min and max Version of a package is specified in that isc. Does it make sense that if a range is specified that there should also be a way to specify what the defaultChannel for that range should be?

Maybe something like the following in an isc?:

```
      packages:
        - name: ibm-mq
          range:
            minVersion: '1.6.0'
            maxVersion: '1.7.10'
            defaultChannel: 'v1.7'
```

**Comment by dinhxuanvu** [comment]
Hi Joe.
I can see what you try to do with adding the defaultChannel setting in the ImageSetConfig itself. However, it is not gonna solve this issue fully either. If the original default channel is not empty and not the same as the selected default channel in the config, then what happens? Is that an invalid config? My opinion is that oc-mirror users can filter versions and channels that they want but they shouldn't alter the package settings in anyway. The source of truth is still the CatalogSource where the packages locate. Any changes in the package settings should be done in CatalogSource not via oc-mirror.
I personally think that if default channel is no longer an explicit setting for a specific channel, this issue will be resolved. Instead, each channel has its own priority settings and OLM would sort the channels via priority values. Another option is to allow empty channel. Either way, these are my personal thoughts. There is no guarantee if any of these will happen.
I also think it is important to take a more conservative approach to this scenario hence erroring out instead of making some irreversible changes. Users can always modifying the config and rerun. However, it is much more difficult to correct bad installation due to bad default channel settings.

**Comment by joehuizenga** [comment]
@dinhxuanvu Is this kinda what your thinking?

```
{
    "schema": "olm.package",
    "name": "ibm-mq",
    "defaultChannel": "v1.8",   // <-------------- remove this as an option
}
{
    "schema": "olm.channel",
    "name": "v1.6",
    "package": "ibm-mq",

    “<new priority model>”  // <---------------- add new priority setting here, and OLM would implement selection somehow?

    "entries": [
        {
            "name": "ibm-mq.v1.6.0",
            "skipRange": ">=1.0.0 <1.6.0"
        }
    ]
}
```

**Comment by dinhxuanvu** [comment]
Hi Joe,
Correct. That's how I envision. It's basically similar to catalogsource priority. This proposed change would be rather simple to do with FBC. Plus, some changes to the resolver.

**Comment by joehuizenga** [comment]
Vu, if this seems like the right direction, what are the correct next steps to flush this out?

**Comment by dinhxuanvu** [comment]
I would bring this up on upstream OLM given this is FBC. Then go from there.
