### ISSUE TITLE
[RFE] Do not prune operator versions removed from package channels from mirror registry 

### ISSUE THREAD

**Issue by afflom** [openshift/oc-mirror#462]
Summary: It is typical for operator publishers to remove operator versions from package channels with new versions utilizing the skip(range) to queue upgrades from deleted versions. oc-mirror detects this condition as content removed from the imageset and prunes associated images from the deleted version from the mirror registry. This RFE proposes a scheme for overcoming this potentially unexpected behavior. 

User: As a user, if my imageset-config does not change, I do not want content pruned from my mirror registry. 

Proposal: 
1. Mark the associated images of operator versions that are deleted from package channels as obsolete and notionally remove them from the imageset so that they are not factored into differential layer operations. 
2. Provide a CLI flag for pruning obsolete images from the mirror registry. 
3. Maintain the existing workflow and functionality of pruning for images associated with non-deleted operator versions

@jpower432 @dinhxuanvu @jharmison-redhat

**Comment by tjmapley** [comment]
I second this issue.

We need to lock in on particular operator versions and still get updates for other operators.

**Workaround:** Mirror to the disconnected registry as a user w/o permissions to delete images. In Harbor, I think this is the `Developer` role.

**Comment by duritong** [comment]
There are tons of operator publishers that only publish one version.

You can't use oc-mirror with them since oc-mirror removes the content gone from the bundle and thus removes content still used on configured clusters. This can take workload done, since images might not be available anymore when pods land on nodes that do not (yet) have the image referenced by the gone version.

We could say that oc-mirror should only clean up versions below `minVersion` /`startingVersion`. But I guess: How does it still know about older versions, if they are gone from the bundle? Well the references would at least still be in the mirrored registry.
